baseurl = "https://lgb.dk"
languageCode = "en-us"
title = "Lasse Bjerre Portfolio"
disqusShortname = "lgbdk"

[params]
    tagline = "Portfolio"

[author]
    name = "Lasse Bjerre"
    profilePicture = "/img/profile.jpg"
    mail = "lasse@lgb.dk"
    github = "https://github.com/Ordspilleren"
    linkedin = "https://dk.linkedin.com/in/lgb"
